# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matthew Harris 
email: matthewh806@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        Personal website of Matthew Harris
baseurl: "/index" # the subpath of your site, e.g. /blog
url: "https://yourdomain.com://matthewh806.github.io" #the base hostname & protocol for your site
github_username:  matthewh80

# Build settings
markdown: kramdown

# Ignore directories / files
exclude: [vendor]
